//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

use super::location_city_tbl;
use super::location_county_tbl;
use super::location_district_tbl;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "location_city_tbl")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub location_city_code: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub location_county_code: i32,
    pub location_city: String,
    pub reg_dt: DateTime,
    pub chg_dt: Option<DateTime>,
    pub reg_id: String,
    pub chg_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::location_county_tbl::Entity",
        from = "Column::LocationCountyCode",
        to = "super::location_county_tbl::Column::LocationCountyCode"
    )]
    LocationCountyTbl,
    #[sea_orm(has_many = "super::location_district_tbl::Entity")]
    LocationDistrictTbl,
}

impl Related<location_county_tbl::Entity> for location_city_tbl::Entity {
    fn to() -> RelationDef {
        Relation::LocationCountyTbl.def()
    }
}

impl Related<location_district_tbl::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LocationDistrictTbl.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
