//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

use super::location_city_tbl;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "location_district_tbl")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub location_district_code: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub location_city_code: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub location_county_code: i32,
    pub location_district: String,
    pub reg_dt: DateTime,
    pub chg_dt: Option<DateTime>,
    pub reg_id: String,
    pub chg_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::location_city_tbl::Entity",
        from = "Column::LocationCityCode",
        to = "super::location_city_tbl::Column::LocationCityCode"
    )]
    LocationCityTbl,
    #[sea_orm(
        belongs_to = "super::location_city_tbl::Entity",
        from = "Column::LocationCountyCode",
        to = "super::location_city_tbl::Column::LocationCountyCode"
    )]
    LocationCountyTbl,
}

impl Related<location_city_tbl::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LocationCityTbl.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
