//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

use super::location_city_tbl;
use super::location_county_tbl;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "location_county_tbl")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub location_county_code: i32,
    pub location_county: String,
    pub reg_dt: DateTime,
    pub chg_dt: Option<DateTime>,
    pub reg_id: String,
    pub chg_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::location_city_tbl::Entity")]
    LocationCityTbl,
}

impl Related<location_city_tbl::Entity> for location_county_tbl::Entity {
    fn to() -> RelationDef {
        Relation::LocationCityTbl.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
