//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub mod prelude;

pub mod brand_tbl;
pub mod elastic_index_info_tbl;
pub mod location_city_tbl;
pub mod location_county_tbl;
pub mod location_district_tbl;
pub mod migrations;
pub mod recommend_tbl;
pub mod store;
pub mod store_location_info_tbl;
pub mod store_old;
pub mod store_recommend_tbl;
pub mod store_type_link_tbl;
pub mod store_type_major;
pub mod store_type_sub;
pub mod user_auth_tbl;
pub mod user_detail_tbl;
pub mod user_tbl;
pub mod users;
pub mod zero_possible_market;
pub mod zero_possible_market_backup;
