//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::brand_tbl::Entity as BrandTbl;
pub use super::elastic_index_info_tbl::Entity as ElasticIndexInfoTbl;
pub use super::location_city_tbl::Entity as LocationCityTbl;
pub use super::location_county_tbl::Entity as LocationCountyTbl;
pub use super::location_district_tbl::Entity as LocationDistrictTbl;
pub use super::migrations::Entity as Migrations;
pub use super::recommend_tbl::Entity as RecommendTbl;
pub use super::store::Entity as Store;
pub use super::store_location_info_tbl::Entity as StoreLocationInfoTbl;
pub use super::store_old::Entity as StoreOld;
pub use super::store_recommend_tbl::Entity as StoreRecommendTbl;
pub use super::store_type_link_tbl::Entity as StoreTypeLinkTbl;
pub use super::store_type_major::Entity as StoreTypeMajor;
pub use super::store_type_sub::Entity as StoreTypeSub;
pub use super::user_auth_tbl::Entity as UserAuthTbl;
pub use super::user_detail_tbl::Entity as UserDetailTbl;
pub use super::user_tbl::Entity as UserTbl;
pub use super::users::Entity as Users;
pub use super::zero_possible_market::Entity as ZeroPossibleMarket;
pub use super::zero_possible_market_backup::Entity as ZeroPossibleMarketBackup;
