//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;

use crate::entity::store_type_major;
use crate::entity::store_type_sub;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "store_type_major")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    major_type: i32,
    type_name: String,
    pub reg_dt: DateTime,
    pub chg_dt: Option<DateTime>,
    pub reg_id: String,
    pub chg_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::store_type_sub::Entity")]
    StoreTypeSub,
}

impl Related<store_type_sub::Entity> for store_type_major::Entity {
    fn to() -> RelationDef {
        Relation::StoreTypeSub.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
