//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_tbl")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub user_no: i32,
    pub user_nm: String,
    pub reg_dt: Option<DateTime>,
    pub reg_id: Option<String>,
    pub chg_dt: Option<DateTime>,
    pub chg_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
