//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_detail_tbl")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub detail_no: i32,
    pub user_no: i32,
    pub addr_type: Option<String>,
    pub addr: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((10, 7)))", nullable)]
    pub lng_x: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 7)))", nullable)]
    pub lat_y: Option<Decimal>,
    pub reg_dt: Option<DateTime>,
    pub reg_id: Option<String>,
    pub chg_dt: Option<DateTime>,
    pub chg_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
